#!/usr/bin/env bash
# stripe_webhook_loop.sh — turnkey Stripe webhook idempotency demo (A3) against the
# LOCAL Supabase stack. Proves: a checkout.session.completed event is verified
# (real Stripe t=,v1= HMAC), recorded once, and a RESEND of the same event.id
# dedupes to NOOP (no double-fulfill — the A3 headline).
#
# The ONE prerequisite you must do yourself (interactive, browser): `stripe login`.
# Everything else — webhook secret, backend, listener, trigger, resend, and the
# before/after ledger proof — this script does.
#
# Receive/verify/dedupe needs only the webhook secret (auto-generated by
# `stripe listen`), NOT a sk_test_ key: the secret signs forwarded events and the
# simulated adapter verifies them offline over the identical HMAC path (INV-9). So
# STRIPE_MODE stays `simulate`; flip it to `live` + add STRIPE_SECRET_KEY only when
# you also want OUTBOUND Stripe calls.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
PORT="${PORT:-8000}"
ENDPOINT="localhost:${PORT}/payments/webhook"
ENV_FILE="backend/.env.local-supabase"
LOG_DIR="$(mktemp -d)"
BACKEND_LOG="$LOG_DIR/backend.log"
LISTEN_LOG="$LOG_DIR/stripe_listen.log"
BACKEND_PID=""
LISTEN_PID=""

say()  { printf '\n\033[1;36m== %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

cleanup() {
  [ -n "$LISTEN_PID" ]  && kill "$LISTEN_PID"  2>/dev/null || true
  [ -n "$BACKEND_PID" ] && kill "$BACKEND_PID" 2>/dev/null || true
  say "logs kept at: $LOG_DIR"
}
trap cleanup EXIT

# --- Preflight ---------------------------------------------------------------
command -v stripe >/dev/null || die "stripe CLI not found (brew install stripe/stripe-cli/stripe)."
[ -f "$ENV_FILE" ] || die "missing $ENV_FILE — provision the local Supabase stack first."

set -a; . "$ENV_FILE"; set +a
# Auth WITHOUT `stripe login`: if a test secret key is in the repo .env, hand it to
# the CLI via STRIPE_API_KEY (the CLI honors this env var) — no browser pairing.
# Falls back to an existing `stripe login` session if no key is present.
if [ -f .env ]; then SK="$(grep -E '^STRIPE_SECRET_KEY=' .env | head -1 | cut -d= -f2- | tr -d '"' )"; fi
case "${SK:-}" in
  sk_test_*) export STRIPE_API_KEY="$SK"; say "using STRIPE_SECRET_KEY from .env (no stripe login needed)" ;;
  sk_live_*) die "refusing a LIVE key (sk_live_) — use a TEST key (sk_test_) for this demo (NFR-1)." ;;
esac
# Either the env key or a prior `stripe login` must let the CLI talk to Stripe.
if ! stripe listen --print-secret >/dev/null 2>&1; then
  die "stripe is not authenticated. Either put a sk_test_ key in .env (STRIPE_SECRET_KEY=) or run: stripe login"
fi

[ -n "${DATABASE_URL:-}" ] || die "DATABASE_URL not set by $ENV_FILE."
psql "$DATABASE_URL" -tAc "select 1" >/dev/null 2>&1 || die "local Supabase DB unreachable at DATABASE_URL — is 'supabase start' up?"

WHSEC="$(stripe listen --print-secret)"
say "webhook secret obtained from stripe listen (whsec_…${WHSEC: -6})"

# --- Start the backend with the demo env -------------------------------------
say "starting backend on :$PORT (STRIPE_MODE=simulate, payments store = local Supabase)"
( cd backend && \
  STRIPE_WEBHOOK_SECRET="$WHSEC" STRIPE_MODE=simulate COCKPIT_REPO=auto \
  GT_PROGRAM_ID=fall_enrollment AUTH_MODE=demo \
  uv run uvicorn app.main:app --port "$PORT" >"$BACKEND_LOG" 2>&1 ) &
BACKEND_PID=$!

# /families is auth-gated (401), so "server responding with any HTTP code" = up.
up=""
for _ in $(seq 1 60); do
  code="$(curl -s -o /dev/null -w "%{http_code}" "localhost:${PORT}/families" 2>/dev/null || echo 000)"
  [ "$code" != "000" ] && { up=1; break; }
  sleep 0.5
done
[ -n "$up" ] || { tail -20 "$BACKEND_LOG"; die "backend did not start (no HTTP response on :$PORT)"; }

# --- Start the forwarder -----------------------------------------------------
say "forwarding Stripe events → $ENDPOINT"
stripe listen --forward-to "$ENDPOINT" >"$LISTEN_LOG" 2>&1 &
LISTEN_PID=$!
for _ in $(seq 1 40); do grep -q "Ready" "$LISTEN_LOG" 2>/dev/null && break; sleep 0.5; done

ledger() { psql "$DATABASE_URL" -tAc \
  "select (select count(*) from stripe_events), (select count(*) from payment);"; }

say "ledger BEFORE: stripe_events / payment = $(ledger)"

# --- Fire one event ----------------------------------------------------------
say "stripe trigger checkout.session.completed"
stripe trigger checkout.session.completed >/dev/null 2>&1
sleep 4
EVT="$(psql "$DATABASE_URL" -tAc "select event_id from stripe_events order by received_at desc limit 1;" | tr -d '[:space:]')"
say "ledger AFTER trigger:  stripe_events / payment = $(ledger)   (event ${EVT})"
[ -n "$EVT" ] || die "no stripe_events row recorded — check $BACKEND_LOG / $LISTEN_LOG"

# --- Resend the SAME event.id → must dedupe (no double-fulfill) ---------------
say "stripe events resend $EVT   (same event.id → expect NOOP, ledger unchanged)"
stripe events resend "$EVT" >/dev/null 2>&1 || stripe events resend "$EVT" --webhook-endpoint "$ENDPOINT" >/dev/null 2>&1 || true
sleep 4
say "ledger AFTER resend:   stripe_events / payment = $(ledger)"

echo
echo "PROOF: the counts after the resend match the counts after the first trigger —"
echo "the duplicate event.id was deduped to NOOP (A3 idempotency; no double-fulfill)."
echo "Backend log: $BACKEND_LOG    Listener log: $LISTEN_LOG"
