"""Ambassador dual-source reconcile surface (Grassroots) — the HTTP read.

Thin HTTP composition over the pure dual-source reconciler
(:func:`app.core.ambassador_reconcile.reconcile_ambassadors`). The Grassroots
roster is HubSpot's ambassador-tracking property ⊕ the ``community.gt.school``
community export; ``community.gt.school`` is a STOOD-IN source generated by
:mod:`app.data.synthetic_ambassadors` (INV-9 — simulated, labeled, no live
call). The deterministic core decides every row; this router only adapts the two
sources in and the JSON the Grassroots UI's ambassador table + RECONCILED badge
consume out.

``GET /ambassadors/reconcile`` returns:

  - ``union``    — the deduped reconciled rows, each with provenance
    (``both`` / ``hubspot-only`` / ``community-only``) and a conflict flag;
  - ``counts``   — union / matched / per-source-only / conflict counts (derived
    from the union, so they can never disagree with it);
  - ``conflicts``— the surfaced cross-source disagreements (e.g. status differs),
    flagged for a human, never auto-resolved (INV-2/INV-4 posture);
  - ``sources``  — per-source health (row count + simulated freshness) and a
    ``reconciled_minutes_ago`` derived from the oldest contributing source, so
    the badge reflects REAL source state, not a hardcoded "6m ago".

The two sources are injected via :func:`get_ambassador_sources` so tests can
override them with a known fixture (the ``RepositoryDep`` injection pattern of
:mod:`app.api.merge`). The reconciliation is aggregate + adult-only (INV-6).
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends

from app.core.ambassador_reconcile import reconcile_ambassadors
from app.data.synthetic_ambassadors import AmbassadorSources, generate_ambassador_sources

router = APIRouter(tags=["ambassadors"])


def get_ambassador_sources() -> AmbassadorSources:
    """Yield the two stood-in ambassador sources (the reconcile input seam).

    v1 binds the synthetic generator (``community.gt.school`` is not reachable;
    INV-9). Going live = rebinding this to the real HubSpot tracking-property read
    + community export with zero core/router changes. Tests override it with a
    known fixture to assert the reconciler's matched / only / conflict paths.
    """
    return generate_ambassador_sources()


SourcesDep = Annotated[AmbassadorSources, Depends(get_ambassador_sources)]


@router.get("/ambassadors/reconcile", response_model=dict[str, object])
def reconcile(sources: SourcesDep) -> dict[str, object]:
    """Reconcile the two ambassador sources into the union + counts + conflicts.

    Runs the pure :func:`reconcile_ambassadors` over the injected sources and
    shapes its result for the Grassroots UI. ``reconciled_minutes_ago`` is the
    MAX of the two sources' freshness — the reconciled view is only as fresh as
    its oldest contributing source — and ``source_health`` is ``ok`` only when
    both sources returned rows (a structural check, no numeric threshold; INV-11).
    """
    hubspot = sources.hubspot
    community = sources.community
    result = reconcile_ambassadors(list(hubspot.rows), list(community.rows))

    both_present = bool(hubspot.rows) and bool(community.rows)
    reconciled_minutes_ago = max(hubspot.synced_minutes_ago, community.synced_minutes_ago)

    return {
        "union": [row.model_dump(mode="json") for row in result.union],
        "conflicts": [c.model_dump(mode="json") for c in result.conflicts],
        "counts": {
            "union": result.union_count,
            "matched": result.matched_count,
            "hubspot_only": result.hubspot_only_count,
            "community_only": result.community_only_count,
            "conflicts": result.conflict_count,
        },
        "sources": [
            {
                "name": hubspot.name,
                "count": len(hubspot.rows),
                "synced_minutes_ago": hubspot.synced_minutes_ago,
                "healthy": bool(hubspot.rows),
            },
            {
                "name": community.name,
                "count": len(community.rows),
                "synced_minutes_ago": community.synced_minutes_ago,
                "healthy": bool(community.rows),
            },
        ],
        "source_health": "ok" if both_present else "degraded",
        "reconciled_minutes_ago": reconciled_minutes_ago,
    }
